//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forms.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Forms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 290.
        /// </summary>
        internal static string ColorTextX {
            get {
                return ResourceManager.GetString("ColorTextX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 50.
        /// </summary>
        internal static string ColorTextY {
            get {
                return ResourceManager.GetString("ColorTextY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Input Color.
        /// </summary>
        internal static string ColorTxt {
            get {
                return ResourceManager.GetString("ColorTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 200.
        /// </summary>
        internal static string HeigthMain {
            get {
                return ResourceManager.GetString("HeigthMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MainForm.
        /// </summary>
        internal static string MainFormName {
            get {
                return ResourceManager.GetString("MainFormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 50.
        /// </summary>
        internal static string ModalBtnH {
            get {
                return ResourceManager.GetString("ModalBtnH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Modal Form.
        /// </summary>
        internal static string ModalBtnText {
            get {
                return ResourceManager.GetString("ModalBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 100.
        /// </summary>
        internal static string ModalBtnW {
            get {
                return ResourceManager.GetString("ModalBtnW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 290.
        /// </summary>
        internal static string ModalBtnX {
            get {
                return ResourceManager.GetString("ModalBtnX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 100.
        /// </summary>
        internal static string ModalBtnY {
            get {
                return ResourceManager.GetString("ModalBtnY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Input Name.
        /// </summary>
        internal static string NameInputText {
            get {
                return ResourceManager.GetString("NameInputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 290.
        /// </summary>
        internal static string NameInputX {
            get {
                return ResourceManager.GetString("NameInputX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 10.
        /// </summary>
        internal static string NameInputY {
            get {
                return ResourceManager.GetString("NameInputY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 50.
        /// </summary>
        internal static string NoneModalBtnH {
            get {
                return ResourceManager.GetString("NoneModalBtnH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New None Modal Form.
        /// </summary>
        internal static string NoneModalBtnText {
            get {
                return ResourceManager.GetString("NoneModalBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 100.
        /// </summary>
        internal static string NoneModalBtnW {
            get {
                return ResourceManager.GetString("NoneModalBtnW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 10.
        /// </summary>
        internal static string NoneModalBtnX {
            get {
                return ResourceManager.GetString("NoneModalBtnX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 100.
        /// </summary>
        internal static string NoneModalBtnY {
            get {
                return ResourceManager.GetString("NoneModalBtnY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Input Heigth.
        /// </summary>
        internal static string SizeHText {
            get {
                return ResourceManager.GetString("SizeHText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 150.
        /// </summary>
        internal static string SizeHX {
            get {
                return ResourceManager.GetString("SizeHX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 50.
        /// </summary>
        internal static string SizeHY {
            get {
                return ResourceManager.GetString("SizeHY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Input Width.
        /// </summary>
        internal static string SizeWText {
            get {
                return ResourceManager.GetString("SizeWText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 150.
        /// </summary>
        internal static string SizeWX {
            get {
                return ResourceManager.GetString("SizeWX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 10.
        /// </summary>
        internal static string SizeWY {
            get {
                return ResourceManager.GetString("SizeWY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 10.
        /// </summary>
        internal static string TextXLocX {
            get {
                return ResourceManager.GetString("TextXLocX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 10.
        /// </summary>
        internal static string TextXLocY {
            get {
                return ResourceManager.GetString("TextXLocY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 10.
        /// </summary>
        internal static string TextYLocX {
            get {
                return ResourceManager.GetString("TextYLocX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 50.
        /// </summary>
        internal static string TextYLocY {
            get {
                return ResourceManager.GetString("TextYLocY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 400.
        /// </summary>
        internal static string WidthMain {
            get {
                return ResourceManager.GetString("WidthMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Input X.
        /// </summary>
        internal static string XText {
            get {
                return ResourceManager.GetString("XText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Input Y.
        /// </summary>
        internal static string YText {
            get {
                return ResourceManager.GetString("YText", resourceCulture);
            }
        }
    }
}
